@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name helloWorld
GET {{baseUrl}}/
Content-Type: application/json

{
  "name": "Luis"
}

###

# @name register
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "luis@gmail.com",
  "name": "luis",
  "password": "admin"
}


###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "luis@gmail.com",
  "password": "admin"
}
